services:
  postgres:
    container_name: skistore-database
    image: postgres:13.16-bookworm
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
      - skistore
    volumes:
      - skistore-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    environment:
      POSTGRES_DB: skistore-database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    container_name: skistore-redis
    image: redis:8.0-M02-alpine3.21
    restart: always
    ports:
      - "6379:6379"
    networks:
      - skistore
    volumes:
      - skistore-redis:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  skistore-data:
    name: skistore-data
  skistore-redis:
    name: skistore-redis

networks:
  skistore:
    name: skistore-network
    driver: bridge
    external: false
