name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  BUCKET_NAME: "${{ secrets.STATE_BUCKET_NAME }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up AWS/Terraform CLI
        run: |
          sudo snap refresh
          sudo snap install aws-cli --classic
          sudo snap install terraform --classic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Terraform State S3 bucket if not exists
        run: |
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket doesn't exist. Creating..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" --create-bucket-configuration LocationConstraint="$AWS_REGION"
          else
            echo "Bucket already exists. Skipping creation."
          fi

      - name: Encrypt Terraform State S3 bucket
        run: |
          ENCRYPTION_STATUS=$(aws s3api get-bucket-encryption --bucket "$BUCKET_NAME" 2>/dev/null || true)
          
          if echo "$ENCRYPTION_STATUS" | grep -q '"SSEAlgorithm": "aws:kms"'; then
            echo "Bucket is already encrypted with KMS. Skipping."
          else
          
          echo "Applying encryption settings..."
          aws s3api put-bucket-encryption --bucket "$BUCKET_NAME" --server-side-encryption-configuration '{
            "Rules": [
              {
                ApplyServerSideEncryptionByDefault": {
                  "SSEAlgorithm": "aws:kms"
                }
              }
            ]
          }'
          fi
 
      - name: Block all public ACL / policy
        run: |
          aws s3api put-public-access-block --bucket "$BUCKET_NAME" --public-access-block-configuration '{
            "BlockPublicAcls": true,
            "IgnorePublicAcls": true,
            "BlockPublicPolicy": true,
            "RestrictPublicBuckets": true
          }'

      - name: Enable Bucket Versioning
        run: |
          get_bucket_versioning_policy=$(aws s3api get-bucket-versioning --bucket $BUCKET_NAME)
          get_policy_status=$(echo "$get_bucket_versioning_policy" | jq -r '.Status')

          if [ -z "$get_policy_status" ]; then
            aws s3api put-bucket-versioning --bucket $BUCKET_NAME --versioning-configuration Status=Enabled
          else
            echo "Bucket is already versioned. Skipping changes."
          fi

      - name: Terraform Init
        working-directory: ./infrastructure/terraform/environments/prod
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create DynamoDB Lock Table if not exists
        working-directory: ./infrastructure/terraform/environments/prod
        run: |
          TABLE_NAME="${{ secrets.LOCK_IN_DYNAMO_TABLE_NAME }}"

          if ! aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$AWS_REGION" 2>/dev/null; then
            echo "Table doesn't exist. Creating via Terraform."
            terraform apply -lock=false \
              -target=aws_dynamodb_table.terraform_locks \
              -var="region=${{ secrets.AWS_REGION }}" \
              -var="project_name=${{ secrets.TF_PROJECT_NAME }}" \
              -var="db_user=${{ secrets.TF_DB_USER }}" \
              -var="db_pass=${{ secrets.TF_DB_PASS }}" \
              -auto-approve
          else
            echo "Lock table already exists. Skipping creation."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        working-directory: ./infrastructure/terraform/environments/prod
        run: |
          terraform plan -input=false \
            -var="region=${{ secrets.AWS_REGION }}" \
            -var="project_name=${{ secrets.TF_PROJECT_NAME }}" \
            -var="db_user=${{ secrets.TF_DB_USER }}" \
            -var="db_pass=${{ secrets.TF_DB_PASS }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Terraform Apply
      #   working-directory: ./infrastructure/terraform/environments/prod
      #   run: |
      #     terraform apply -input=false -auto-approve \
      #       -var="region=${{ secrets.AWS_REGION }}" \
      #       -var="project_name=${{ secrets.TF_PROJECT_NAME }}" \
      #       -var="db_user=${{ secrets.TF_DB_USER }}" \
      #       -var="db_pass=${{ secrets.TF_DB_PASS }}"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
